version: 2.1

jobs:
  job-0:
    docker:
      - image: composer:2
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: List files
          command: ls -la
          working_directory: save-and-restore-cache
      - run:
          name: Confirm sizes
          command: du -h -d 1
          working_directory: save-and-restore-cache
      # - restore_cache:
      #     keys:
      #       - npm-v1-{{ checksum "save-and-restore-cache/package-lock.json" }}
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "save-and-restore-cache/composer.lock" }}
      # - run:
      #     name: Install Node.js packages
      #     command: npm install
      - run:
          name: Install PHP packages
          command: composer install
          working_directory: save-and-restore-cache
      - run:
          name: List files
          command: ls -la
          working_directory: save-and-restore-cache
      - run:
          name: Confirm sizes
          command: du -h -d 1
          working_directory: save-and-restore-cache
      # - save_cache:
      #     key: npm-v1-{{ checksum "save-and-restore-cache/package-lock.json" }}
      #     paths:
      #       - node_modules
      - save_cache:
          key: composer-v1-{{ checksum "save-and-restore-cache/composer.lock" }}
          paths:
            - vendor
  job-1:
    docker:
      - image: composer:2
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: List files
          command: ls -la
          working_directory: save-and-restore-cache
      - run:
          name: Confirm sizes
          command: du -h -d 1
          working_directory: save-and-restore-cache
      # - restore_cache:
      #     keys:
      #       - npm-v1-{{ checksum "save-and-restore-cache/package-lock.json" }}
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "save-and-restore-cache/composer.lock" }}
      # - run:
      #     name: Install Node.js packages
      #     command: npm install
      - run:
          name: Install PHP packages
          command: composer install
          working_directory: save-and-restore-cache
      - run:
          name: List files
          command: ls -la
          working_directory: save-and-restore-cache
      - run:
          name: Confirm sizes
          command: du -h -d 1
          working_directory: save-and-restore-cache

workflows:
  version: 2.1
  workflow-0:
    jobs:
      - job-0
      - job-1:
          requires:
            - job-0
