version: 2.1

jobs:
  job-0:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: Create directory for persistence
          command: mkdir -p workspace
          working_directory: /home/circleci
      - run: 
          name: Create file
          command: echo hello > hello
          working_directory: /home/circleci/workspace
      - run: 
          name: Create another file
          command: echo bye > bye
          working_directory: /home/circleci/workspace
      - persist_to_workspace:
          root: /home/circleci/workspace
          paths:
            - *
  job-1:
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/workspace
      - run: 
          name: List files
          command: ls -l
          working_directory: /home/circleci/workspace
      - run: 
          name: Browse file
          command: cat hello
          working_directory: /home/circleci/workspace

workflows:
  version: 2.1
  workflow-0:
    jobs:
      - job-0
      - job-1:
          requires:
            - job-0
